In [1]:
# # in google colab uncomment this

# import os

# os.system('apt-get install -y xvfb')
# os.system('wget https://raw.githubusercontent.com/yandexdataschool/Practical_DL/fall18/xvfb -O ../xvfb')
# os.system('apt-get install -y python-opengl ffmpeg')
# os.system('pip install pyglet==1.2.4')

# os.system('python -m pip install -U pygame --user')

# print('setup complete')

# XVFB will be launched if you run on a server
import os
if type(os.environ.get("DISPLAY")) is not str or len(os.environ.get("DISPLAY")) == 0:
    !bash ../xvfb start
    %env DISPLAY = : 1

# Implementing Advantage-Actor Critic (A2C)

In this notebook you will implement Advantage Actor Critic algorithm that trains on a batch of Atari 2600 environments running in parallel. 

Firstly, we will use environment wrappers implemented in file `atari_wrappers.py`. These wrappers preprocess observations (resize, grayscal, take max between frames, skip frames and stack them together) and rewards. Some of the wrappers help to reset the environment and pass `done` flag equal to `True` when agent dies.
File `env_batch.py` includes implementation of `ParallelEnvBatch` class that allows to run multiple environments in parallel. To create an environment we can use `nature_dqn_env` function. Note that if you are using 
PyTorch and not using `tensorboardX` you will need to implement a wrapper that will log **raw** total rewards that the *unwrapped* environment returns and redefine the implemention of `nature_dqn_env` function here. 



In [2]:
import numpy as np
from atari_wrappers import nature_dqn_env


env = nature_dqn_env("SpaceInvadersNoFrameskip-v4", nenvs=8)
obs = env.reset()
assert obs.shape == (8, 84, 84, 4) # 8 个环境并行，84x84单色，4帧合并 
assert obs.dtype == np.uint8
print(env.action_space) # Discrete(6) 0-5
print(env.action_space.sample()) # 8 个环境并行 ,每个连续按动同一个动作 

entry_point is :gym.envs.atari:AtariEnv
entry_point is :gym.envs.atari:AtariEnv


/home/jim/.local/lib/python3.6/site-packages/gym/envs/registration.py:14: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
  result = entry_point.load(require = False)


entry_point is :gym.envs.atari:AtariEnv
entry_point is :gym.envs.atari:AtariEnv


/home/jim/.local/lib/python3.6/site-packages/gym/envs/registration.py:14: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
  result = entry_point.load(require = False)
/home/jim/.local/lib/python3.6/site-packages/gym/envs/registration.py:14: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
  result = entry_point.load(require = False)
/home/jim/.local/lib/python3.6/site-packages/gym/envs/registration.py:14: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
  result = entry_point.load(require = False)


entry_point is :gym.envs.atari:AtariEnv
entry_point is :gym.envs.atari:AtariEnv
entry_point is :gym.envs.atari:AtariEnv


/home/jim/.local/lib/python3.6/site-packages/gym/envs/registration.py:14: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
  result = entry_point.load(require = False)
/home/jim/.local/lib/python3.6/site-packages/gym/envs/registration.py:14: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
  result = entry_point.load(require = False)
/home/jim/.local/lib/python3.6/site-packages/gym/envs/registration.py:14: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
  result = entry_point.load(require = False)


entry_point is :gym.envs.atari:AtariEnv


/home/jim/.local/lib/python3.6/site-packages/gym/envs/registration.py:14: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
  result = entry_point.load(require = False)


[4 5 0 3 3 3 1 3]


Next, we will need to implement a model that predicts logits and values. It is suggested that you use the same model as in [Nature DQN paper](https://web.stanford.edu/class/psych209/Readings/MnihEtAlHassibis15NatureControlDeepRL.pdf) with a modification that instead of having a single output layer, it will have two output layers taking as input the output of the last hidden layer. **Note** that this model is different from the model you used in homework where you implemented DQN. You can use your favorite deep learning framework here. We suggest that you use orthogonal initialization with parameter $\sqrt{2}$ for kernels and initialize biases with zeros. 

In [3]:
# import tensorflow as torch
# import torch as tf
import mxnet as mx
# <Define your model here>
class my_model_class(mx.gluon.nn.HybridBlock):
    def __init__(self, **kwargs):
        super(my_model_class, self).__init__(**kwargs)
        self.net = mx.gluon.nn.HybridSequential()
        self.net.add(mx.gluon.nn.Conv2D(channels=4,layout="NCHW",kernel_size=3))
        self.net.add(mx.gluon.nn.Conv2D(channels=16,layout="NCHW",kernel_size=3))
        self.net.add(mx.gluon.nn.Conv2D(channels=16,layout="NCHW",kernel_size=2))
        self.net.add(mx.gluon.nn.Conv2D(channels=8,layout="NCHW",kernel_size=2))
        self.net.add(mx.gluon.nn.Conv2D(channels=4,layout="NCHW",kernel_size=3))
        self.net.add(mx.gluon.nn.AvgPool2D(layout="NCHW",pool_size=2))
        #
        self.actions_conv2d = mx.gluon.nn.Conv2D(channels=1,layout="NCHW",kernel_size=3)
        self.actions_desen = mx.gluon.nn.Dense(6,activation='relu')
        #
        self.values_conv2d = mx.gluon.nn.Conv2D(channels=1,layout="NCHW",kernel_size=3)
        self.values_desen = mx.gluon.nn.Dense(1,activation='sigmoid')
    def hybrid_forward(self,F,x):
        middle_x = self.net(x)
        y_actions = self.actions_conv2d(middle_x)
        y_actions = self.actions_desen(y_actions)
        y_values = self.values_conv2d(middle_x)
        y_values = self.values_desen(y_values)
        return y_actions, y_values

model = my_model_class()
print(model)
model.initialize(init=mx.init.Xavier())
model.hybridize()

my_model_class(
  (net): HybridSequential(
    (0): Conv2D(None -> 4, kernel_size=(3, 3), stride=(1, 1))
    (1): Conv2D(None -> 16, kernel_size=(3, 3), stride=(1, 1))
    (2): Conv2D(None -> 16, kernel_size=(2, 2), stride=(1, 1))
    (3): Conv2D(None -> 8, kernel_size=(2, 2), stride=(1, 1))
    (4): Conv2D(None -> 4, kernel_size=(3, 3), stride=(1, 1))
    (5): AvgPool2D(size=(2, 2), stride=(2, 2), padding=(0, 0), ceil_mode=False, global_pool=False, pool_type=avg, layout=NCHW)
  )
  (actions_conv2d): Conv2D(None -> 1, kernel_size=(3, 3), stride=(1, 1))
  (actions_desen): Dense(None -> 6, Activation(relu))
  (values_conv2d): Conv2D(None -> 1, kernel_size=(3, 3), stride=(1, 1))
  (values_desen): Dense(None -> 1, Activation(sigmoid))
)


You will also need to define and use a policy that wraps the model. While the model computes logits for all actions, the policy will sample actions and also compute their log probabilities.  `policy.act` should return a dictionary of all the arrays that are needed to interact with an environment and train the model.
 Note that actions must be an `np.ndarray` while the other
tensors need to have the type determined by your deep learning framework. 

In [4]:
class Policy:
  def __init__(self, model):
    self.model = model
    
  def act(self, inputs):
    # Implement policy by calling model, sampling actions and computing their log probs>
    # Should return a dict containing keys ['actions', 'logits', 'log_probs', 'values'].
    y_actions, y_values = self.model(inputs) # y_values 就是 V_hat_t(s_t,theata_v) 
    #print(y_actions.shape)
    #print(y_values.shape)
    rel = {}
    logits = mx.nd.softmax(y_actions,axis=-1)
    #print(logits.shape)
    rel['logits'] = logits
    m,n = logits.shape
    rel['actions'] = []
    for i in np.arange(m):
        probs = logits[i,:].asnumpy()
        #print(probs)
        rel['actions'].append(np.random.choice(np.array([0,1,2,3,4,5]),1,p = probs)[0])
    #print(rel['actions'])
    log_probs = mx.nd.log_softmax(y_actions,axis=-1)
    rel['log_probs'] = log_probs
    rel['values'] = y_values
    return rel

test_policy = Policy(model)
inputs = mx.nd.random.uniform(low=0, high=255,shape = (8,4,48,48),dtype='float32')
print(inputs.shape)
rel = test_policy.act(inputs)

(8, 4, 48, 48)


Next will pass the environment and policy to a runner that collects partial trajectories from the environment. 
The class that does is is already implemented for you.

In [5]:
from runners import EnvRunner

This runner interacts with the environment for a given number of steps and returns a dictionary containing
keys 

* 'observations' 
* 'rewards' 
* 'resets'
* 'actions'
* all other keys that you defined in `Policy`

under each of these keys there is a python `list` of interactions with the environment of specified length $T$ &mdash; the size of partial trajectory. 

To train the part of the model that predicts state values you will need to compute the value targets. 
Any callable could be passed to `EnvRunner` to be applied to each partial trajectory after it is collected. 
Thus, we can implement and use `ComputeValueTargets` callable. 
The formula for the value targets is simple:

$$
\hat v(s_t) = \sum_{t'=0}^{T - 1}\gamma^{t'}r_{t+t'} + \gamma^T \hat{v}(s_{t+T}),
$$

In implementation, however, do not forget to use 
`trajectory['resets']` flags to check if you need to add the value targets at the next step when 
computing value targets for the current step. You can access `trajectory['state']['latest_observation']`
to get last observations in partial trajectory &mdash; $s_{t+T}$.

In [24]:
class ComputeValueTargets():
  def __init__(self, policy, gamma=0.99):
    self.policy = policy
    self.gamma = gamma
  def __call__(self, trajectory):
    # This method should modify trajectory inplace by adding 
    # an item with key 'value_targets' to it. 
    # <Compute value targets for a given partial trajectory>
    T = len(trajectory)
    print(T)
    t_array = mx.nd.array([i for i in range(T)])
    gamma_array = mx.nd.ones(shape=(T,2)) * self.gamma
    gamma_array[:,0] = gamma_array[:,0] ** t_array
    gamma_array[:,1] = gamma_array[:,1] ** T
    print(gamma_array)
    print(trajectory['rewards'])
    laster_v = [trajectory['values'][-1].asscalar() for i in range(T)]
    print(laster_v)
    r_v_array = mx.nd.array([trajectory['rewards'], laster_v]).T
    print(r_v_array)
    v_hat_s_t_array = mx.nd.sum(gamma_array * r_v_array, axis = 1)
    print(v_hat_s_t_array)
    rel = [mx.nd.sum(v_hat_s_t_array[i:]).asscalar() for i in np.arange(T)]
    return rel    
test = ComputeValueTargets(policy = [1,2,3])
rel['rewards'] = [i for i in range(len(rel))]
print(test(rel))

6

[[1.         0.9414802 ]
 [0.99       0.9414802 ]
 [0.98010004 0.9414802 ]
 [0.970299   0.9414802 ]
 [0.960596   0.9414802 ]
 [0.9509901  0.9414802 ]]
<NDArray 6x2 @cpu(0)>
[0, 1, 2, 3, 4, 5]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

[[0. 0.]
 [1. 0.]
 [2. 0.]
 [3. 0.]
 [4. 0.]
 [5. 0.]]
<NDArray 6x2 @cpu(0)>

[0.        0.99      1.9602001 2.910897  3.842384  4.7549505]
<NDArray 6 @cpu(0)>
[14.458431, 14.458431, 13.468431, 11.508232, 8.597335, 4.7549505]


After computing value targets we will transform lists of interactions into tensors
with the first dimension `batch_size` which is equal to `T * nenvs`, i.e. you essentially need
to flatten the first two dimensions. 

In [ ]:
class MergeTimeBatch:
  """ Merges first two axes typically representing time and env batch. """
  def __call__(self, trajectory):
    # Modify trajectory inplace. 
    # <TODO: implement>
    

In [ ]:
model = <Create your model here>
policy = Policy(model)
runner = EnvRunner(env, policy, nsteps=5,
                   transforms=[ComputeValueTargets(),
                               MergeTimeBatch()])

Now is the time to implement the advantage actor critic algorithm itself. You can look into your lecture,
[Mnih et al. 2016](https://arxiv.org/abs/1602.01783) paper, and [lecture](https://www.youtube.com/watch?v=Tol_jw5hWnI&list=PLkFD6_40KJIxJMR-j5A1mkxK26gh_qg37&index=20) by Sergey Levine.

In [ ]:
class A2C:
  def __init__(self,
               policy,
               optimizer,
               value_loss_coef=0.25,
               entropy_coef=0.01,
               max_grad_norm=0.5):
    self.policy = policy
    self.optimizer = optimizer
    self.value_loss_coef = value_loss_coef
    self.entropy_coef = entropy_coef
    self.max_grad_norm = max_grad_norm
    
  def policy_loss(self, trajectory):
    # You will need to compute advantages here. 
    <TODO: implement>
    
  def value_loss(self, trajectory):
    <TODO: implement>
    
  def loss(self, trajectory):
    <TODO: implement>
      
  def step(self, trajectory):
    <TODO: implement>

Now you can train your model. With reasonable hyperparameters training on a single GTX1080 for 10 million steps across all batched environments (which translates to about 5 hours of wall clock time)
it should be possible to achieve *average raw reward over last 100 episodes* (the average is taken over 100 last 
episodes in each environment in the batch) of about 600. You should plot this quantity with respect to 
`runner.step_var` &mdash; the number of interactions with all environments. It is highly 
encouraged to also provide plots of the following quantities (these are useful for debugging as well):

* [Coefficient of Determination](https://en.wikipedia.org/wiki/Coefficient_of_determination) between 
value targets and value predictions
* Entropy of the policy $\pi$
* Value loss
* Policy loss
* Value targets
* Value predictions
* Gradient norm
* Advantages
* A2C loss

For optimization we suggest you use RMSProp with learning rate starting from 7e-4 and linearly decayed to 0, smoothing constant (alpha in PyTorch and decay in TensorFlow) equal to 0.99 and epsilon equal to 1e-5.

In [ ]:
a2c = <Create instance of the algorithm> 

<Write your training loop>